version: "2"
services:
  kitten:
    image: ipepe/kitten
    hostname: kitten.ipepe.pl
    container_name: kitten-nginx
    restart: always
    network_mode: bridge
    expose:
      - 80
    environment:
      VIRTUAL_HOST: kitten.ipepe.pl
      LETSENCRYPT_HOST: kitten.ipepe.pl
      LETSENCRYPT_EMAIL: letsencrypt@ipepe.pl

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    network_mode: bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/conf:/etc/nginx/conf.d
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:ro
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-proxy-docker-gen
    network_mode: bridge
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - ./data/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    network_mode: bridge
    depends_on:
      - nginx-proxy
      - docker-gen
    volumes_from:
      - nginx-proxy
    volumes:
      - ./data/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
